// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"blog/app/model/internal"
)

// Attachments is the golang structure for table attachments.
type Attachments internal.Attachments

// Fill with you ideas below.
