// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"blog/app/model/internal"
)

// Links is the golang structure for table links.
type Links internal.Links

// Fill with you ideas below.
