// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"blog/app/model/internal"
)

// Menus is the golang structure for table menus.
type Menus internal.Menus

// Fill with you ideas below.
