// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"blog/app/model/internal"
)

// Options is the golang structure for table options.
type Options internal.Options

// Fill with you ideas below.
