// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"blog/app/model/internal"
)

// PostTags is the golang structure for table post_tags.
type PostTags internal.PostTags

// Fill with you ideas below.
