// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"blog/app/model/internal"
)

// Posts is the golang structure for table posts.
type Posts internal.Posts

// Fill with you ideas below.
