// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"blog/app/model/internal"
)

// Tags is the golang structure for table tags.
type Tags internal.Tags

// Fill with you ideas below.
