// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Links is the golang structure for table links.
type Links struct {
	Id          int         `orm:"id,primary"  json:"id"`          //
	CreateTime  *gtime.Time `orm:"create_time" json:"createTime"`  //
	UpdateTime  *gtime.Time `orm:"update_time" json:"updateTime"`  //
	Description string      `orm:"description" json:"description"` //
	Logo        string      `orm:"logo"        json:"logo"`        //
	Name        string      `orm:"name"        json:"name"`        //
	Priority    int         `orm:"priority"    json:"priority"`    //
	Team        string      `orm:"team"        json:"team"`        //
	Url         string      `orm:"url"         json:"url"`         //
}
