// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Options is the golang structure for table options.
type Options struct {
	Id          int         `orm:"id,primary"   json:"id"`          //
	CreateTime  *gtime.Time `orm:"create_time"  json:"createTime"`  //
	UpdateTime  *gtime.Time `orm:"update_time"  json:"updateTime"`  //
	OptionKey   string      `orm:"option_key"   json:"optionKey"`   //
	Type        int         `orm:"type"         json:"type"`        //
	OptionValue string      `orm:"option_value" json:"optionValue"` //
}
