// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Posts is the golang structure for table posts.
type Posts struct {
	Type            int         `orm:"type"             json:"type"`            //
	Id              int         `orm:"id,primary"       json:"id"`              //
	CreateTime      *gtime.Time `orm:"create_time"      json:"createTime"`      //
	UpdateTime      *gtime.Time `orm:"update_time"      json:"updateTime"`      //
	DisallowComment int         `orm:"disallow_comment" json:"disallowComment"` //
	EditTime        *gtime.Time `orm:"edit_time"        json:"editTime"`        //
	EditorType      int         `orm:"editor_type"      json:"editorType"`      //
	FormatContent   string      `orm:"format_content"   json:"formatContent"`   //
	Likes           int64       `orm:"likes"            json:"likes"`           //
	MetaDescription string      `orm:"meta_description" json:"metaDescription"` //
	MetaKeywords    string      `orm:"meta_keywords"    json:"metaKeywords"`    //
	OriginalContent string      `orm:"original_content" json:"originalContent"` //
	Password        string      `orm:"password"         json:"password"`        //
	Slug            string      `orm:"slug,unique"      json:"slug"`            //
	Status          int         `orm:"status"           json:"status"`          //
	Summary         string      `orm:"summary"          json:"summary"`         //
	Template        string      `orm:"template"         json:"template"`        //
	Thumbnail       string      `orm:"thumbnail"        json:"thumbnail"`       //
	Title           string      `orm:"title"            json:"title"`           //
	TopPriority     int         `orm:"top_priority"     json:"topPriority"`     //
	Url             string      `orm:"url"              json:"url"`             //
	Visits          int64       `orm:"visits"           json:"visits"`          //
	WordCount       int64       `orm:"word_count"       json:"wordCount"`       //
}
