// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// PostTags is the golang structure for table post_tags.
type PostTags struct {
	Id         int         `orm:"id,primary"  json:"id"`         //
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` //
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` //
	PostId     int         `orm:"post_id"     json:"postId"`     //
	TagId      int         `orm:"tag_id"      json:"tagId"`      //
}
