// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Tags is the golang structure for table tags.
type Tags struct {
	Id         int         `orm:"id,primary"  json:"id"`         //
	CreateTime *gtime.Time `orm:"create_time" json:"createTime"` //
	UpdateTime *gtime.Time `orm:"update_time" json:"updateTime"` //
	Name       string      `orm:"name"        json:"name"`       //
	Slug       string      `orm:"slug,unique" json:"slug"`       //
	SlugName   string      `orm:"slug_name"   json:"slugName"`   //
	Thumbnail  string      `orm:"thumbnail"   json:"thumbnail"`  //
}
