// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Users is the golang structure for table users.
type Users struct {
	Id          int         `orm:"id,primary"  json:"id"`          //
	CreateTime  *gtime.Time `orm:"create_time" json:"createTime"`  //
	UpdateTime  *gtime.Time `orm:"update_time" json:"updateTime"`  //
	Avatar      string      `orm:"avatar"      json:"avatar"`      //
	Description string      `orm:"description" json:"description"` //
	Email       string      `orm:"email"       json:"email"`       //
	ExpireTime  *gtime.Time `orm:"expire_time" json:"expireTime"`  //
	MfaKey      string      `orm:"mfa_key"     json:"mfaKey"`      //
	MfaType     int         `orm:"mfa_type"    json:"mfaType"`     //
	Nickname    string      `orm:"nickname"    json:"nickname"`    //
	Password    string      `orm:"password"    json:"password"`    //
	Username    string      `orm:"username"    json:"username"`    //
}
