// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"blog/app/dao/internal"
)

// postsDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type postsDao struct {
	internal.PostsDao
}

var (
	// Posts is globally public accessible object for table posts operations.
	Posts = postsDao{
		internal.Posts,
	}
)

// Fill with you ideas below.
