// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"blog/app/dao/internal"
)

// tagsDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type tagsDao struct {
	internal.TagsDao
}

var (
	// Tags is globally public accessible object for table tags operations.
	Tags = tagsDao{
		internal.Tags,
	}
)

// Fill with you ideas below.
